export const SQS_EVENT_TYPES = {
  GENERATE_FIRST_INVOICE: 'GENERATE_FIRST_INVOICE',
  GENERATE_INVOICE: 'GENERATE_INVOICE',

  ATTACH_CHARGES: 'ATTACH_CHARGES',
  CHARGE_NOTIFICATION: 'CHARGE_NOTIFICATION',

  PROCESS_PAYMENT: 'PROCESS_PAYMENT',

  SEND_REMINDER: 'SEND_REMINDER',
  SEND_WHATSAPP: 'SEND_WHATSAPP',
  PAYMENT_CONFIRMATION: 'PAYMENT_CONFIRMATION',
} as const;
